# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

es:
  languageCode: es-mx
  contentDir: content/es

# en:
#   languageCode: en-us
#   contentDir: content/en
